import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
const fixture = JSON.parse(await readFile('.data/http-smoke.json', 'utf8'));
const origin = process.env.APP_ORIGIN || 'http://localhost:3000';
const checks: string[] = [];
async function api(path: string, cookie = fixture.admin, body?: unknown, expected = 200) { const response = await fetch(origin + path, { method: body === undefined ? 'GET' : 'POST', headers: { Cookie: 'kanban_session=' + cookie, Origin: origin, 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); assert.equal(response.status, expected, path + ': ' + response.status); return response; }
await api('/api/state', '', undefined, 401); checks.push('匿名访问被拒绝');
await api('/api/media/' + fixture.mediaId + '?ticket=new', fixture.member, undefined, 404); checks.push('未确认来源附件仅提交者可见');
const ticket = await (await api('/api/media/' + fixture.mediaId + '?ticket=new')).json(); const image = await api(ticket.url); assert.equal(image.headers.get('content-type'), 'image/gif'); assert.equal((await image.arrayBuffer()).byteLength > 0, true); await api(ticket.url.replace('expires=', 'expires=0'), fixture.admin, undefined, 403); checks.push('附件字节可读，篡改短期签名被拒绝');
const created = await (await api('/api/state', fixture.admin, { op: 'createTask', task: { title: 'HTTP 测试任务', type: 'other', customer: '虚构客户', description: '', checklist: ['核对测试资料'], ownerId: null, dueDate: '2026-09-15' } })).json();
const responses = await Promise.all(['第一条并发进展','第二条并发进展'].map(text => fetch(origin + '/api/state', { method: 'POST', headers: { Cookie: 'kanban_session=' + fixture.admin, Origin: origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ op: 'comment', taskId: created.taskId, version: 1, text }) }))); assert.deepEqual(responses.map(r => r.status).sort(), [200,409]); checks.push('两个并发修改只有一个成功，另一个收到 409');
await api('/api/state', fixture.admin, { op: 'append', taskId: created.taskId, version: 2, sourceIds: [fixture.sourceId] }); const memberTicket = await (await api('/api/media/' + fixture.mediaId + '?ticket=new', fixture.member)).json(); await api(memberTicket.url, fixture.member); checks.push('追加正式任务后团队成员可读取附件');
const invite = await (await api('/api/state', fixture.admin, { op: 'invite' })).json(); const joined = await api('/api/auth', '', { op: 'join', invitation: invite.invitation, name: '邀请测试', login: 'invite-user', password: 'test-passphrase-12345' }); assert.match(joined.headers.get('set-cookie') || '', /HttpOnly/i); await api('/api/auth', '', { op: 'join', invitation: invite.invitation, name: '重复邀请测试', login: 'replay-user', password: 'test-passphrase-12345' }, 400); checks.push('邀请可加入团队且只能使用一次');
await api('/api/state', fixture.admin, { op: 'removeMember', memberId: fixture.memberId }); await api('/api/state', fixture.member, undefined, 401); await api(memberTicket.url, fixture.member, undefined, 401); checks.push('移除成员后旧会话和未过期附件链接立即失效');
const csrf = await fetch(origin + '/api/state', { method: 'POST', headers: { Cookie: 'kanban_session=' + fixture.admin, Origin: 'https://unrelated.invalid', 'Content-Type': 'application/json' }, body: JSON.stringify({ op: 'binding' }) }); assert.equal(csrf.status, 403); checks.push('跨站写请求被拒绝');
const report = { at: new Date().toISOString(), passed: checks.length, checks }; await writeFile('evidence/http-smoke-report.json', JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2));
