'use client';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, Bookmark, Check, CheckCheck, ChevronDown, Columns3, FileText, Inbox, LayoutGrid, MoreHorizontal, Plus, Search, Sparkles, Users, X, Paperclip, Clock3,  } from 'lucide-react';
import './demo.css';
const sources = [
 ['滑动图标按钮','andrew-demchenk0','Buttons/andrew-demchenk0_splendid-impala-69.html','将删除按钮改为新建任务；保留图标滑动，缩短行程并保留文字。'],
 ['柔光搜索框','alexruix','Inputs/alexruix_slippery-frog-10.html','保留聚焦边框与外圈，用鼠尾草绿替换粉色。'],
 ['收藏反馈','Galahhad','Checkboxes/Galahhad_mighty-warthog-42.html','保留书签回弹，缩小粒子范围；支持键盘操作。'],
 ['紧凑开关','Galahhad','Toggle-switches/Galahhad_heavy-dog-14.html','滑动圆点用于紧凑模式，移除日夜图案。'],
 ['任务操作菜单','Galahhad','Checkboxes/Galahhad_old-falcon-43.html','保留浮层与分组，改用原生 details / summary 操作。'],
 ['资料叠层卡片','alexruix','Cards/alexruix_cold-cat-38.html','四层彩虹减为两层低饱和绿，悬停收拢。'],
];
const initial = [
 {id:1,title:'准备车险续保方案',client:'林先生 · 两车一房',type:'保险服务',owner:'Zack',status:0,date:'今天',priority:true,note:'核对两辆车的续保价格，整理可选保障差异。',files:3},
 {id:2,title:'核对客户补充资料',client:'陈女士 · 新业务',type:'资料核对',owner:'Mia',status:0,date:'明天',priority:false,note:'补齐驾驶记录与现有保单，确认拟生效日期。',files:2},
 {id:3,title:'整理商业险报价',client:'North Studio · 企业客户',type:'保险服务',owner:'Zack',status:1,date:'今天',priority:true,note:'比较三家公司的责任限额及免赔额。',files:4},
 {id:4,title:'更新客户联系信息',client:'王先生 · 客户维护',type:'客户服务',owner:'Leo',status:1,date:'周一',priority:false,note:'已收到地址变更资料，待核对并回访。',files:1},
 {id:5,title:'确认房屋保障细节',client:'刘女士 · 房险续保',type:'客户服务',owner:'Mia',status:2,date:'明天',priority:false,note:'等待客户确认地下室用途与房屋更新年份。',files:2},
 {id:6,title:'完成新客户建档',client:'周先生 · 新客户',type:'资料核对',owner:'Zack',status:3,date:'已完成',priority:false,note:'客户资料与联系记录已整理完成。',files:2},
];
const stages=['待处理','进行中','等待回复','已完成'];
export default function DesignDemo(){
 const [page,setPage]=useState('看板'); const [tasks,setTasks]=useState(initial); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('全部任务'); const [compact,setCompact]=useState(false); const [saved,setSaved]=useState<number[]>([3]); const [detail,setDetail]=useState<number|null>(null); const [adding,setAdding]=useState(false); const [draft,setDraft]=useState(''); const [notice,setNotice]=useState(''); const [credits,setCredits]=useState(false); const [plan,setPlan]=useState(1);
 const task=tasks.find(t=>t.id===detail);
 const visible=tasks.filter(t=>(t.title+t.client+t.owner).toLowerCase().includes(query.toLowerCase())&&(filter==='全部任务'||filter==='我的任务'&&t.owner==='Zack'||filter==='已收藏'&&saved.includes(t.id)));
 function move(id:number,status:number){setTasks(ts=>ts.map(t=>t.id===id?{...t,status}:t));setNotice(`任务已移至「${stages[status]}」`);}
 return <div className={`gd ${compact?'gd-compact':''}`}>
 <aside className="gd-sidebar"><a className="gd-brand" href="/"><span><CheckCheck size={23}/></span>Team Kanban</a><div className="gd-workspace"><span className="gd-avatar">C</span><div>Cantrust 团队<small>协作工作空间</small></div><ChevronDown size={14}/></div><small className="gd-nav-caption">WORKSPACE</small><nav>{[[LayoutGrid,'看板'],[Inbox,'收件箱'],[Users,'团队'],[Columns3,'保险对比']].map(([Icon,label])=>{const I=Icon as typeof LayoutGrid;return <button key={String(label)} className={page===label?'active':''} onClick={()=>{setPage(String(label));setQuery('');}}><I size={18}/>{String(label)}{label==='收件箱'&&<b>3</b>}</button>;})}</nav><div className="gd-side-note"><Sparkles size={18}/><strong>熟悉的工作，更轻的界面。</strong><p>Galaxy × Team Kanban<br/>交互设计演示 · 01</p><button onClick={()=>setCredits(true)}>查看入选组件 <ArrowRight size={14}/></button></div><div className="gd-user"><span className="gd-avatar">Z</span><div>Zack<small>团队管理员</small></div><a href="/" aria-label="返回原看板"><ArrowLeft size={17}/></a></div></aside>
 <div className="gd-main"><header className="gd-top"><span>工作空间 <span>/</span> {page}</span><div><span className="gd-demo-tag">交互演示 · 示例数据</span><button onClick={()=>setCredits(true)}>组件来源 ↗</button></div></header>
 <main><div className="gd-heading"><div><p className="gd-eyebrow">A LITTLE CALMER. A LOT CLEARER.</p><h1>{page==='看板'?'让每件事，有条不紊。':page==='收件箱'?'让资料，找到归处。':page==='团队'?'一起，把事情做好。':'把方案，比较清楚。'}</h1><p> {page==='看板'?'从待办到完成，团队的每一步都清晰可见。':'统一的控件与视觉语言，贯穿每一个工作场景。'}</p></div><button className="gd-create" onClick={()=>{setAdding(true);setDraft('');}}><span>新建任务</span><i><Plus size={19}/></i></button></div>
 <section className="gd-stats"><div><small>工作进行时</small><strong>{tasks.filter(t=>t.status!==3).length.toString().padStart(2,'0')}<span> 项待推进</span></strong></div><div><small>今天重点关注</small><strong>{tasks.filter(t=>t.priority&&t.status!==3).length.toString().padStart(2,'0')}<span> 项优先任务</span></strong></div><div><small>已完成</small><strong>{tasks.filter(t=>t.status===3).length.toString().padStart(2,'0')}<span> 项事务</span></strong></div><div className="gd-progress"><div><span>工作进度</span><b>{Math.round(tasks.filter(t=>t.status===3).length/tasks.length*100)}%</b></div><progress max={tasks.length} value={tasks.filter(t=>t.status===3).length}/><small>每完成一件，向前一步。</small></div></section>
 <div className="gd-toolbar"><div className="gd-tabs">{['全部任务','我的任务','已收藏'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'active':''} onClick={()=>{setFilter(f);setPage('看板');}}>{f}</button>)}</div><label className="gd-search"><Search size={16}/><input type="search" aria-label="搜索任务" placeholder="搜索任务或客户…" value={query} onChange={e=>{setQuery(e.target.value);setPage('看板');}}/></label><label className="gd-toggle"><input type="checkbox" checked={compact} onChange={e=>setCompact(e.target.checked)}/><span><i/></span>紧凑模式</label></div>
 {page==='看板'&&<div className="gd-board">{stages.map((stage,s)=><section className={`gd-column gd-stage-${s}`} key={stage}><header><div><i/>{stage}<b>{visible.filter(t=>t.status===s).length}</b></div><Plus size={15}/></header>{visible.filter(t=>t.status===s).map(t=><article className="gd-card" key={t.id}><div className="gd-card-top"><span className={`gd-tag gd-tag-${t.type==='保险服务'?'green':t.type==='资料核对'?'blue':'sand'}`}>{t.type}</span><button className={`gd-bookmark ${saved.includes(t.id)?'on':''}`} aria-label={`收藏${t.title}`} aria-pressed={saved.includes(t.id)} onClick={()=>setSaved(v=>v.includes(t.id)?v.filter(i=>i!==t.id):[...v,t.id])}><Bookmark size={16}/></button></div><button className="gd-card-title" onClick={()=>setDetail(t.id)}>{t.title}</button><p className="gd-client">{t.client}</p><p className="gd-description">{t.note}</p>{t.priority&&<span className="gd-priority"><i/>优先处理</span>}<div className="gd-card-footer"><span className="gd-owner"><i>{t.owner[0]}</i>{t.owner}</span><span><Paperclip size={12}/>{t.files}</span><details className="gd-menu"><summary aria-label={`${t.title}操作`}><MoreHorizontal size={17}/></summary><div>{stages.map((name,i)=><button key={name} disabled={i===t.status} onClick={e=>{move(t.id,i);e.currentTarget.closest('details')?.removeAttribute('open');}}>{name}{i===t.status&&<Check size={12}/>}</button>)}</div></details></div><div className="gd-date"><Clock3 size={12}/>{t.date}<button onClick={()=>move(t.id,t.status===3?0:3)}>{t.status===3?'重新打开':'标记完成'}<Check size={12}/></button></div></article>)}{!visible.some(t=>t.status===s)&&<div className="gd-empty">暂时没有任务<br/><small>留一点空间，给下一步。</small></div>}</section>)}</div>}
 {page==='收件箱'&&<section className="gd-inbox">{['客户补充资料','房屋保障文件','车辆续保信息'].map((name,i)=><article className="gd-stack" key={name}><FileText size={30}/><span className="gd-tag gd-tag-green">待整理 · {i+2} 个文件</span><h2>{name}</h2><p>示例资料包 · 团队共享</p><button onClick={()=>{setDraft(`整理${name}`);setAdding(true);}}>转为任务 <ArrowRight size={16}/></button></article>)}</section>}
 {page==='团队'&&<section className="gd-team">{['Zack','Mia','Leo'].map((name,i)=><article key={name}><span className="gd-avatar">{name[0]}</span><h2>{name}</h2><p>{i===0?'团队管理员':'团队成员'}</p><hr/><strong>{tasks.filter(t=>t.owner===name&&t.status!==3).length} 项进行中的事务</strong><button onClick={()=>{setPage('看板');setFilter('全部任务');setQuery(name);setNotice(`正在查看 ${name} 的任务`);}}>查看工作 <ArrowRight size={14}/></button></article>)}</section>}
 {page==='保险对比'&&<section className="gd-plans">{['现有保险','方案一','方案二'].map((name,i)=><article key={name} className={plan===i?'selected':''}><span className="gd-tag gd-tag-green">{plan===i?'当前选择':'可比较方案'}</span><h2>{name}</h2><p>{['Maple Insurance','Northern Assurance','Evergreen Mutual'][i]} · 示例公司</p><strong>${['6,240','5,131','5,760'][i]}<small> / 年</small></strong><ul><li><Check size={14}/>两辆汽车 + 一处房屋</li><li><Check size={14}/>责任险 2M</li><li><Check size={14}/>碰撞起赔额 $1,000</li></ul><button onClick={()=>setPlan(i)}>{plan===i?'已选此方案':'选择此方案'}<Check size={15}/></button></article>)}</section>}
 <footer className="gd-footer"><span><span className="gd-dot"/> 演示改动仅在当前页面有效</span><button onClick={()=>{setTasks(initial);setSaved([3]);setQuery('');setFilter('全部任务');setNotice('演示数据已重置');}}>重置演示</button><button onClick={()=>setCredits(true)}>6 个入选元素 · 查看设计说明 ↗</button></footer>
 </main></div>
 {(adding||task||credits)&&<dialog className="gd-overlay" ref={node=>{if(node&&!node.open)node.showModal();}} onCancel={()=>{setAdding(false);setDetail(null);setCredits(false);}} aria-label={credits?'组件来源':adding?'新建任务':'任务详情'}><section className="gd-panel"><button className="gd-close" autoFocus onClick={()=>{setAdding(false);setDetail(null);setCredits(false);}} aria-label="关闭"><X size={20}/></button>{credits?<><p className="gd-eyebrow">THE CURATED COLLECTION</p><h2>六个元素，一套工作语言。</h2><p>筛选自 Uiverse Galaxy，按当前工作空间改编。原始源码与 MIT 许可保存在项目 docs/galaxy-sources。</p>{sources.map(([name,author,path,why],i)=><div className="gd-source" key={name}><small>0{i+1} / {author}</small><h3>{name}</h3><p>{why}</p><a href={`https://github.com/uiverse-io/galaxy/blob/main/${path}`} target="_blank" rel="noreferrer">查看原组件 ↗</a></div>)}</>:adding?<form onSubmit={e=>{e.preventDefault();if(!draft.trim())return;setTasks(ts=>[...ts,{...initial[0],id:Date.now(),title:draft.trim(),client:'示例客户 · 新任务',note:'在演示板中创建的任务。',priority:false,files:0}]);setAdding(false);setPage('看板');setQuery('');setFilter('全部任务');setNotice('任务已添加到待处理');}}><p className="gd-eyebrow">MAKE ROOM FOR THE NEXT STEP</p><h2>新建一项任务</h2><label className="gd-field">任务名称<input required maxLength={100} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="接下来，需要做什么？"/></label><p>仅添加至当前演示板，刷新后恢复示例数据。</p><button className="gd-solid" type="submit">创建任务 <Plus size={16}/></button></form>:task&&<><span className="gd-tag gd-tag-green">{task.type}</span><h2>{task.title}</h2><p>{task.client}</p><p className="gd-detail-note">{task.note}</p><label className="gd-field">任务状态<select value={task.status} onChange={e=>move(task.id,Number(e.target.value))}>{stages.map((s,i)=><option key={s} value={i}>{s}</option>)}</select></label><p>负责人 · {task.owner}</p><button className="gd-solid" onClick={()=>{move(task.id,3);setDetail(null);}}>标记完成 <Check size={16}/></button></>}</section></dialog>}
 {notice&&<div className="gd-toast" role="status"><CheckCheck size={18}/>{notice}<button onClick={()=>setNotice('')} aria-label="关闭提示"><X size={15}/></button></div>}
 </div>;
}
